services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"  # שינוי הפורט החיצוני ל-27018
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:
